# Data Transformation in Pandas

Hi Guys, Welcome to [Tirendaz Academy](https://youtube.com/c/tirendazacademy) 😀
</br>
In this notebook, I'm going to show data transformation in Pandas.
</br>
Happy Learning 🐱‍🏍 

In [1]:
import pandas as pd

In [2]:
data=pd.DataFrame({"a":["one","two"]*3,
                   "b":[1,1,2,3,2,3]})
data

a  b
0  one  1
1  two  1
2  one  2
3  two  3
4  one  2
5  two  3

In [3]:
data.duplicated()

0    False
1    False
2    False
3    False
4     True
5     True
dtype: bool

In [3]:
data.drop_duplicates()

a  b
0  one  1
1  two  1
2  one  2
3  two  3

In [5]:
data["c"]=range(6)
data

a  b  c
0  one  1  0
1  two  1  1
2  one  2  2
3  two  3  3
4  one  2  4
5  two  3  5

In [6]:
data.duplicated(["a","b"],keep="last")

0    False
1    False
2     True
3     True
4    False
5    False
dtype: bool

In [4]:
df=pd.DataFrame({"names":["Tim","tom","Sam",
                          "kate","Kim"],
                "scores":[60,50,70,80,40]})
df

names  scores
0   Tim      60
1   tom      50
2   Sam      70
3  kate      80
4   Kim      40

In [5]:
classes={"Tim":"A","Tom":"A","Sam":"B",
         "Kate":"B","Kim":"B"}

In [6]:
n=df["names"].str.capitalize()

In [7]:
df["branches"]=n.map(classes)

In [8]:
df

names  scores branches
0   Tim      60        A
1   tom      50        A
2   Sam      70        B
3  kate      80        B
4   Kim      40        B

In [14]:
s=pd.Series([80,70,90,60])
s

0    80
1    70
2    90
3    60
dtype: int64

In [9]:
import numpy as np

In [11]:
s.replace(70,np.nan)

0    80.0
1     NaN
2    90.0
3    60.0
dtype: float64

In [12]:
s.replace([70,60],[np.nan,0])

0    80.0
1     NaN
2    90.0
3     0.0
dtype: float64

In [16]:
# s.replace({x:y}) substitui todas as occorencias de x por y
s.replace({90:100,60:0})

0     80
1     70
2    100
3      0
dtype: int64

In [17]:
df=pd.DataFrame(
    np.arange(12).reshape(3,4),
    index=[0,1,2],
    columns=["tim","tom","kim","sam"])
df

tim  tom  kim  sam
0    0    1    2    3
1    4    5    6    7
2    8    9   10   11

In [18]:
s=pd.Series(["one","two","three"])
df.index=df.index.map(s)

In [19]:
df

tim  tom  kim  sam
one      0    1    2    3
two      4    5    6    7
three    8    9   10   11

In [20]:
df.rename(index=str.title,columns=str.upper)

TIM  TOM  KIM  SAM
One      0    1    2    3
Two      4    5    6    7
Three    8    9   10   11

In [19]:
df.rename(index={"one":"ten"},
          columns={"sam":"kate"},
          inplace=True)
df

tim  tom  kim  kate
ten      0    1    2     3
two      4    5    6     7
three    8    9   10    11

In [20]:
sc=[30,80,40,90,60,45,95,75,55,100,65,85]

In [21]:
x=[20,40,60,80,100]

In [22]:
y=pd.cut(sc,x)
y

[(20, 40], (60, 80], (20, 40], (80, 100], (40, 60], ..., (60, 80], (40, 60], (80, 100], (60, 80], (80, 100]]
Length: 12
Categories (4, interval[int64, right]): [(20, 40] < (40, 60] < (60, 80] < (80, 100]]

In [24]:
y.codes

array([0, 2, 0, 3, 1, 1, 3, 2, 1, 3, 2, 3], dtype=int8)

In [26]:
y.categories

IntervalIndex([(20, 40], (40, 60], (60, 80], (80, 100]],
              closed='right',
              dtype='interval[int64]')

In [30]:
# Deprecated pd.value_counts(obj)
pd.Series(y).value_counts()

(80, 100]    4
(40, 60]     3
(60, 80]     3
(20, 40]     2
Name: count, dtype: int64

In [33]:
y=pd.cut(sc,x,right=False)
y

[[20, 40), [80, 100), [40, 60), [80, 100), [60, 80), ..., [60.0, 80.0), [40.0, 60.0), NaN, [60.0, 80.0), [80.0, 100.0)]
Length: 12
Categories (4, interval[int64, left]): [[20, 40) < [40, 60) < [60, 80) < [80, 100)]

In [34]:
nm=["low", "medium", "high", "very high"]
pd.cut(sc,x,labels=nm)

['low', 'high', 'low', 'very high', 'medium', ..., 'high', 'medium', 'very high', 'high', 'very high']
Length: 12
Categories (4, object): ['low' < 'medium' < 'high' < 'very high']

In [36]:
pd.cut(sc,10)

[(29.93, 37.0], (79.0, 86.0], (37.0, 44.0], (86.0, 93.0], (58.0, 65.0], ..., (72.0, 79.0], (51.0, 58.0], (93.0, 100.0], (58.0, 65.0], (79.0, 86.0]]
Length: 12
Categories (10, interval[float64, right]): [(29.93, 37.0] < (37.0, 44.0] < (44.0, 51.0] < (51.0, 58.0] ... (72.0, 79.0] < (79.0, 86.0] < (86.0, 93.0] < (93.0, 100.0]]

In [31]:
data=np.random.randn(100)
c=pd.qcut(data,4)
c

[(-0.135, 0.631], (0.631, 2.286], (-0.629, -0.135], (0.631, 2.286], (-2.186, -0.629], ..., (-0.629, -0.135], (0.631, 2.286], (0.631, 2.286], (-0.135, 0.631], (-0.629, -0.135]]
Length: 100
Categories (4, interval[float64]): [(-2.186, -0.629] < (-0.629, -0.135] < (-0.135, 0.631] < (0.631, 2.286]]

In [32]:
pd.value_counts(c)

(0.631, 2.286]      25
(-0.135, 0.631]     25
(-0.629, -0.135]    25
(-2.186, -0.629]    25
dtype: int64

In [38]:
data=pd.DataFrame(np.random.randn(1000,4))
data.head()

0         1         2         3
0  1.043678  1.151736  1.914473  1.205685
1  2.092141 -0.353215 -1.389741  1.043936
2  0.004428 -0.304587  0.664536 -0.055785
3 -0.516113 -1.488419 -0.110938 -0.077528
4 -0.313655 -1.276636 -2.101642  0.604473

In [34]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.048690     0.030168    -0.050958    -0.004881
std       0.991747     0.996656     0.992911     1.021762
min      -2.999425    -3.514219    -2.864107    -3.186480
25%      -0.723203    -0.622904    -0.726046    -0.752119
50%      -0.058605     0.027484    -0.036939     0.023319
75%       0.560961     0.654890     0.605512     0.739495
max       3.952527     3.491917     3.074154     3.002287

In [39]:
col=data[1]

In [36]:
col[np.abs(col)>3]

4      3.491917
117    3.098920
311   -3.067095
903   -3.514219
Name: 1, dtype: float64

In [44]:
data[(np.abs(data)>3).any(1)]

TypeError: DataFrame.any() takes 1 positional argument but 2 were given

In [45]:
np.sign(data).head()

0    1    2    3
0  1.0  1.0  1.0  1.0
1  1.0 -1.0 -1.0  1.0
2  1.0 -1.0  1.0 -1.0
3 -1.0 -1.0 -1.0 -1.0
4 -1.0 -1.0 -1.0  1.0

In [46]:
data=pd.DataFrame(
    np.arange(12).reshape(4,3))
data

0   1   2
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11

In [49]:
rw=np.random.permutation(4)
rw

array([2, 1, 3, 0], dtype=int32)

In [50]:
data.take(rw)

0   1   2
2  6   7   8
1  3   4   5
3  9  10  11
0  0   1   2

In [51]:
data.sample()

0  1  2
2  6  7  8

In [43]:
data.sample(n=2)

0  1  2
0  0  1  2
2  6  7  8

## Dummy Variable

In [52]:
data=pd.DataFrame(
    {"letter":["c","b","a","b","b","a"],
                   "number":range(6)})
data

letter  number
0      c       0
1      b       1
2      a       2
3      b       3
4      b       4
5      a       5

In [45]:
pd.get_dummies(data["letter"])

a  b  c
0  0  0  1
1  0  1  0
2  1  0  0
3  0  1  0
4  0  1  0
5  1  0  0

In [53]:
data=np.random.randn(10)
data

array([-0.99320991,  0.06342845, -1.54729291, -2.41590044, -0.31175657,
       -0.57097468, -1.40900889,  0.58374094, -0.80053218, -0.6298335 ])

In [55]:
pd.get_dummies(pd.cut(data,4))

(-2.419, -1.666]  (-1.666, -0.916]  (-0.916, -0.166]  (-0.166, 0.584]
0             False              True             False            False
1             False             False             False             True
2             False              True             False            False
3              True             False             False            False
4             False             False              True            False
5             False             False              True            False
6             False              True             False            False
7             False             False             False             True
8             False             False              True            False
9             False             False              True            False

Don't forget to follow us on [YouTube](http://youtube.com/tirendazacademy) | [Medium](http://tirendazacademy.medium.com) | [Twitter](http://twitter.com/tirendazacademy) | [GitHub](http://github.com/tirendazacademy) | [Linkedin](https://www.linkedin.com/in/tirendaz-academy) | [Kaggle](https://www.kaggle.com/tirendazacademy) 😎